name: google-tpu-workshop
channels:
  - defaults
  - conda-forge
  - huggingface
dependencies:
  - python=3.8
  - numpy=1.23.5
  - pandas=1.2.5
  - six=1.15.0
  - pip=21.0.1
  - jupyter
  - jupyterlab_code_formatter
  - black
  - isort
  - biopython=1.79
  - matplotlib=3.5.2
  - neptune-client=0.14.3
  - protobuf=3.20.2
  - regex=2022.1.18
  - tqdm=4.56.0
  - joblib=1.2.0
  - python-dotenv=0.21.0
  - transformers=4.25.1
  - pip:
      - --find-links https://storage.googleapis.com/jax-releases/libtpu_releases.html
      - jax[tpu]==0.3.25
      - jaxlib==0.3.25
      - dm-haiku==0.0.9
      - fair-esm==1.0.2
      - optax==0.1.4
      - scikit-learn==1.0.2
      - torch==1.11.0
      - sentencepiece==0.1.97
      - zstandard==0.20.0
      - datasets==2.10.1
      - cryptography==38.0.4
      - datasets==2.10.1
      - zstandard==0.20.0
      - tensorflow==2.12.0
      - tensorflow-datasets==4.9.2
